// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXT6pMbRseXEyzmsbCgqd5dtveWYLB9rc',
    appId: '1:362867090129:web:3eec92b64be6c6f0f01bf0',
    messagingSenderId: '362867090129',
    projectId: 'builder-3d920',
    authDomain: 'builder-3d920.firebaseapp.com',
    storageBucket: 'builder-3d920.appspot.com',
    measurementId: 'G-9688F5LTWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAURLoi9yktU6ywtOClCfQfaHsnBcc7q78',
    appId: '1:362867090129:android:3cf603a61d3169c0f01bf0',
    messagingSenderId: '362867090129',
    projectId: 'builder-3d920',
    storageBucket: 'builder-3d920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRF8A65_wQWCj09Qa9TCs-j7HkoHxKI-0',
    appId: '1:362867090129:ios:42f321f9daf0dcd8f01bf0',
    messagingSenderId: '362867090129',
    projectId: 'builder-3d920',
    storageBucket: 'builder-3d920.appspot.com',
    iosClientId: '362867090129-26kq0m4mrfp3f5mgj2if814qp9jgidum.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRF8A65_wQWCj09Qa9TCs-j7HkoHxKI-0',
    appId: '1:362867090129:ios:12db97521f640b1ef01bf0',
    messagingSenderId: '362867090129',
    projectId: 'builder-3d920',
    storageBucket: 'builder-3d920.appspot.com',
    iosClientId: '362867090129-tofn0208okp4s3ff74utlmv3g41lntpc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomo.RunnerTests',
  );
}
